# Generated by Django 3.2.12 on 2022-05-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasting_track', '0002_auto_20220521_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastingsession',
            options={'ordering': ('-start_date',)},
        ),
    ]
