# Generated by Django 3.2.12 on 2022-05-08 16:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import ganexa_event_manager.ex_training.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('force_type', models.SmallIntegerField(default=1, help_text='1 for normal weight exercises, 0 for non weight exercises and -1 for assisted exercises', verbose_name='Force type')),
                ('machine', models.BooleanField(default=True, verbose_name='Machine assisted')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercise', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_exercise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name='Display order')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_exercises', to='ex_training.exercise', verbose_name='Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_exercises', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 8, 16, 9, 1, 989311, tzinfo=utc), verbose_name='date')),
                ('units', models.CharField(choices=[(ganexa_event_manager.ex_training.models.WeightUnit['KG'], 'Kilograms'), (ganexa_event_manager.ex_training.models.WeightUnit['LB'], 'Pounds')], default=ganexa_event_manager.ex_training.models.WeightUnit['LB'], max_length=2, verbose_name='Units')),
                ('reps', models.PositiveSmallIntegerField(default=1, verbose_name='Reps')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercisesession', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_sessions', to='ex_training.exercise', verbose_name='Exercise')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_exercisesession', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('weight_units', models.CharField(choices=[(ganexa_event_manager.ex_training.models.WeightUnit['KG'], 'Kilograms'), (ganexa_event_manager.ex_training.models.WeightUnit['LB'], 'Pounds')], default=ganexa_event_manager.ex_training.models.WeightUnit['LB'], max_length=2, verbose_name='Weight units')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Weight')),
                ('height_units', models.CharField(choices=[(ganexa_event_manager.ex_training.models.HeightUnit['M'], 'Meter'), (ganexa_event_manager.ex_training.models.HeightUnit['FT'], 'Feet')], default=ganexa_event_manager.ex_training.models.HeightUnit['M'], max_length=2, verbose_name='Height units')),
                ('height', models.PositiveSmallIntegerField(default=1, verbose_name='Height')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exerciseprofile', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_exerciseprofile', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
