# Generated by Django 3.2.12 on 2022-05-08 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import ganexa_event_manager.ex_training.models


class Migration(migrations.Migration):

    dependencies = [
        ('ex_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprofile',
            name='height',
            field=models.FloatField(default=1, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='exerciseprofile',
            name='height_units',
            field=models.CharField(choices=[('M', 'Meter'), ('FT', 'Feet')], default=ganexa_event_manager.ex_training.models.HeightUnit['M'], max_length=2, verbose_name='Height units'),
        ),
        migrations.AlterField(
            model_name='exerciseprofile',
            name='weight',
            field=models.FloatField(verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='exerciseprofile',
            name='weight_units',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('LB', 'Pounds')], default=ganexa_event_manager.ex_training.models.WeightUnit['LB'], max_length=2, verbose_name='Weight units'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 16, 39, 57, 48495, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='units',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('LB', 'Pounds')], default=ganexa_event_manager.ex_training.models.WeightUnit['LB'], max_length=2, verbose_name='Units'),
        ),
    ]
