# Generated by Django 3.2.12 on 2022-05-21 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ex_training', '0002_auto_20220508_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 54, 17, 402440, tzinfo=utc), verbose_name='date'),
        ),
    ]
