# Generated by Django 3.2.12 on 2022-05-21 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ex_training', '0003_alter_exercisesession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 13, 1, 40, 571927, tzinfo=utc), verbose_name='date'),
        ),
    ]
