# Generated by Django 3.2.12 on 2022-05-22 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ex_training', '0005_alter_exercisesession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 15, 40, 28, 930781, tzinfo=utc), verbose_name='date'),
        ),
    ]
