# Generated by Django 3.2.12 on 2022-06-03 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ex_training', '0006_alter_exercisesession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 11, 51, 8, 717860, tzinfo=utc), verbose_name='date'),
        ),
    ]
