# Generated by Django 3.2.12 on 2022-03-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rangehit',
            options={'ordering': ('-created',)},
        ),
    ]
